### PR TITLE
Podlet v0.3.0

### PR DESCRIPTION
**Pull request by k9withabone**
New release for Podlet!

Includes the usual dependency, README, and CHANGELOG updates.

The current plan is to release on Friday (the 17th) unless something comes up.

### CODE REVIEW

**Comment by cprecioso** [comment]
Hi, I'm looking to get podlet added to homebrew (https://github.com/Homebrew/homebrew-core/pull/172128), will podlet 0.3.0 be tagged soon?

**Comment by k9withabone** [comment]
> will podlet 0.3.0 be tagged soon?

Yes, hopefully soon. It would have been tagged shortly after this PR was merged, but I ran into a permissions issue that I am waiting to be resolved.

**Comment by k9withabone** [comment]
@cprecioso Podlet v0.3.0 is tagged and released!

**Comment by cprecioso** [comment]
@k9withabone and now it's on homebrew :)
https://github.com/Homebrew/homebrew-core/pull/172128

**Comment by cprecioso** [comment]
And added to homebrew too! https://formulae.brew.sh/formula/podlet

**Pull request merged**
